#!/bin/bash

for fname in `ls`
do
  if test $fname
   then
	echo "FILE not null"
  fi
  if test -n $fname
  then
     echo "length is greater than zero"
  fi
  if test -z $fname
  then
    echo "length is equal to zero"
  fi
done

